### ISSUE TITLE
problem: members cannot propose a presentation

### ISSUE THREAD

**Issue by gazhayes** [apacblocks/registration#35]
Problem: people want to propose presentation topics for events.

Solution should allow members to propose a presentation or topic for an event:
- Title of the talk/presentation (max 70 characters)
- Summary of the presentation (max 500 characters)
- An explanation of why should the speaker be taken seriously on this particular topic (qualifications etc). (max 160 characters)

**Comment by gazhayes** [comment]
ping @samuelralak you wanna do this one?

**Comment by samuelralak** [comment]
yep 👍

**Comment by gazhayes** [comment]
The end goal is actually to let members vote on presentations using the same ELO ranking as blockrazor uses for rating wallets etc

**Comment by samuelralak** [comment]
@gazhayes #50 should give the members the ability to propose new topics. Will include the ability to vote in a seperate PR
