### ISSUE TITLE
problem: console errors showing when navigating to /profile

### ISSUE THREAD

**Issue by samuelralak** [apacblocks/registration#37]
Problem: Seeing the below error every time I navigate to the profile page

<img width="1920" alt="Screenshot 2019-09-09 at 03 20 06" src="https://user-images.githubusercontent.com/4476552/64496715-d91acc80-d2b0-11e9-8016-793d46dea151.png">

**Comment by ioioio8888** [comment]
It is beacause of the qr code generator package checks and define the size parameter needs to be int, but it should be also accepting string like '100%', putting '100%' in size still works but will throw this error.

**Comment by gazhayes** [comment]
Since it still works despite the error, I will close this issue.
