### ISSUE TITLE
Problem: Bottom nav action buttons not spread out on desktop

### ISSUE THREAD

**Issue by samuelralak** [apacblocks/registration#39]
Problem: The bottom navigation action buttons do not occupy the entire width of the screen on desktops screen size and instead are instead at the bottom of the screen. This makes the UI on desktops look weird and out of place.

Solutio: Adjust CSS to make bottom navigation buttons occupy the entire width in large screen sizes

**Comment by MadanBhandari** [comment]
I am taking this

**Comment by MadanBhandari** [comment]
Done in PR #49
