### ISSUE TITLE
Problem: User login state disappears upon page refresh

### ISSUE THREAD

**Issue by samuelralak** [apacblocks/registration#40]
Problem: User appears to be "logged out" when page is refreshed - components that should appear when user is logged in disappear. Oddly enough, this is somehow fixed by navigating to the Profile page. 

Solution: Investigate and find fix for problem

**Comment by ioioio8888** [comment]
I think It is because of the user is still 
 logging in after refresh.
Meteor.loggingIn() returns true.

**Comment by samuelralak** [comment]
cool. just figured out how to fix this
