### ISSUE TITLE
problem: last member in member's list is not visible 

### ISSUE THREAD

**Issue by gazhayes** [apacblocks/registration#46]
I haven't checked but probably a UI issue

signed in:

<img width="520" alt="Screenshot 2019-09-11 at 6 06 58 PM" src="https://user-images.githubusercontent.com/8143945/64688522-1c4a8a80-d4bf-11e9-80e8-3261a5e9d3b0.png">

not signed in:

<img width="298" alt="Screenshot 2019-09-11 at 6 10 22 PM" src="https://user-images.githubusercontent.com/8143945/64688690-7b100400-d4bf-11e9-952c-cd97f5987e17.png">

**Comment by gazhayes** [comment]
ping @ioioio8888

**Comment by samuelralak** [comment]
@gazhayes this is a spacing issue. Can be fixed by applying a bottom padding/margin

**Comment by samuelralak** [comment]
Quick fix #48
