### ISSUE TITLE
problem: remaining invites is not accurate

### ISSUE THREAD

**Issue by gazhayes** [apacblocks/registration#58]
problem: clifford choi should have 2 remaining invites because he has not invited anyone. Others may also be innacurate but I haven't checked.

Each member should be able to invite 2 new members.

This is most likely a problem with how the remaining invites are calculated and nothing to do with the integrity of the db.

ping @samuelralak

**Comment by samuelralak** [comment]
yep. the calculation was wrong. pushing a fix in a bit
