### ISSUE TITLE
problem: user data not saved after editing

### ISSUE THREAD

**Issue by gazhayes** [apacblocks/registration#61]
Problem: there's no button in the UI to trigger an upsert (or whatever) for changed data.

Ping @samuelralak

**Comment by samuelralak** [comment]
@gazhayes there's a `SAVE` button on the right corner of the screen. See attached screenshot

<img width="377" alt="Screenshot 2019-09-19 at 11 41 14" src="https://user-images.githubusercontent.com/4476552/65228099-8ae8a300-dad2-11e9-92fb-cf7cbb90358e.png">

**Comment by ioioio8888** [comment]
I changed the format by accident
I solved it in #63
